name: CI-CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        IMAGE_TAG=$(date +%Y%m%d%H%M%S)
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
        docker build -t userjingjing/kube-petclinic-app:$IMAGE_TAG .

    - name: Push Docker image to Docker Hub
      run: docker push userjingjing/kube-petclinic-app:$IMAGE_TAG

    - name: Checkout GitOps repo
      uses: actions/checkout@v3
      with:
        repository: jingjing7065/argo-cd
        ssh-key: ${{ secrets.GITOPS_SSH_KEY }}
        path: gitops

    - name: Update Deployment image tag in GitOps repo
      run: |
        sed -i "s|image: userjingjing/kube-petclinic-app:.*|image: userjingjing/kube-petclinic-app:${{ env.IMAGE_TAG }}|" gitops/deployment.yaml
        cd gitops
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git commit -am "Update image tag to ${{ env.IMAGE_TAG }}"
        git push origin main

